# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/studia_zadania/SR/Systemy_Rekonfigurowalne/lab4/lab4.srcs/sources_1/ip/c_addsub_7/c_addsub_7.xci
# IP: The module: 'c_addsub_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/studia_zadania/SR/Systemy_Rekonfigurowalne/lab4/lab4.gen/sources_1/ip/c_addsub_7/c_addsub_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/studia_zadania/SR/Systemy_Rekonfigurowalne/lab4/lab4.srcs/sources_1/ip/c_addsub_7/c_addsub_7.xci
# IP: The module: 'c_addsub_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/studia_zadania/SR/Systemy_Rekonfigurowalne/lab4/lab4.gen/sources_1/ip/c_addsub_7/c_addsub_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
