# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0_2/src/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0_2/src/c_addsub_0/c_addsub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# XDC: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0_2/src/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0_2/src/c_addsub_0/c_addsub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# XDC: d:/studia_zadania/Systemy_Rekonfigurowalne/lab6/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
